### ISSUE TITLE
Windows Basic theme title bug

### ISSUE THREAD

**Issue by sergeevabc** [Blaukovitch/GOOGLE_CHROME_Windows_7#15]
Setup: Windows 7 SP1 x64 with Windows basic theme enabled (instead of Aero).

* MS Edge 109 works fine

![2024-1116-0223 windows basic theme - ms edge 109](https://github.com/user-attachments/assets/8053ea01-5b7b-4d4f-a497-cfd11a5f4c7c)

* MS Edge 128 does not

![2024-1116-0215 windows basic theme - ms edge 128](https://github.com/user-attachments/assets/6cd684e4-88a7-4e75-a8a8-0ec9bdc149ae)

* Chrome 130 does not

![2024-1116-0219 windows basic theme - chrome 130](https://github.com/user-attachments/assets/ee9172ea-87e7-4f79-ba6b-6eaa7fd65a62)

**Comment by Half-Modern** [comment]
Also happens with classic theme. This was fixed in Supermium, but it will likely require a code modification which is not possible in compiled releases.

**Comment by win32ss** [comment]
The titlebar flickering without DWM was blocked by code in ``hwnd_message_handler.cc``. Specifically, there was code to block window drawing when handling the following messages: WM_SETTEXT, WM_SETICON, WM_NCLBUTTONDOWN and during the calling of user32!EnableMenuItem.

The older Vista-styled basic titlebar still exists in Chromium, but access to it is controlled by the function ThemeHelperWin::ShouldUseNativeFrame() in ``theme_helper_win.cc`` where it only appears if it returns false. The problem is that the function always returns true and is probably optimized out of existence for that reason which means patching will likely be in BrowserDesktopWindowTreeHostWin::GetFrameMode() and BrowserDesktopWindowTreeHostWin::ShouldUseNativeFrame(), both in ``browser_desktop_window_tree_host_win.cc``.
